version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - '5050:5050'
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_client
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    stdin_open: true
    tty: true